# Generated by Django 4.2.2 on 2023-09-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='responsibility',
            field=models.CharField(max_length=40),
        ),
    ]
