# Generated by Django 4.2.2 on 2023-09-15 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_items_date'),
        ('staff', '0003_alter_user_responsibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_item', to='store.items')),
                ('user_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.user')),
            ],
        ),
    ]
