# Generated by Django 4.2.2 on 2023-09-15 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_items_date'),
        ('staff', '0004_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.items'),
        ),
    ]
