# Generated by Django 4.2.2 on 2023-09-16 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_remove_request_user_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='userRequest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.user'),
        ),
    ]
