# Generated by Django 4.2.2 on 2023-09-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_request_userrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='item',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
