# Generated by Django 4.2.2 on 2023-09-16 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='staffDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('userRequest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.user')),
            ],
        ),
    ]
